name: download and parse and git checkin

on:
  push:
  #schedule:
  #  - cron:  '*/10 * * * *' # run every 20min

jobs:
  get_newest_data:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - name: wget daily
      uses: wei/wget@v1
      with:
        args: -O input_data/daily_in_situ_co2_mlo.csv https://scrippsco2.ucsd.edu/assets/data/atmospheric/stations/in_situ_co2/daily/daily_in_situ_co2_mlo.csv
 
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run parsing script
      run: |
        python blend_data.py
        python plot_data.py
    
    - name: Commit report
      run: |
        git config --global user.name 'philshem'
        git config --global user.email 'philshem@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout master
        git commit -am "auto commit - update data"
        git push
